### ISSUE TITLE
[PD] SWOT

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Course-Fundamentals#10]
### Coursework content

https://www.techtarget.com/searchcio/definition/SWOT-analysis-strengths-weaknesses-opportunities-and-threats-analysis

### Estimated time in hours

1

### What is the purpose of this assignment?

Developers need to have a growth mindset because the industry is always changing and growing. Employers look for people who can show they develop and learn.

Think about the key areas that you want to improve on by doing some introspective work and writing your own personal SDOT analysis: 

### Strengths: 
What are you great at?
What makes you personally stand out from other people? 
What positive comments do people say about your strengths?
What are your greatest achievements? 

### Weaknesses :
Where skills do you need to work on? 
Where do you need to improve? i.e coding 
What holds you back? i.e motivation 
What key habits do you want to overcome? 
What do others say about your weaknesses?

### Opportunities :
If I invest my time in my technical skills, I will land a good job..
Who can help me achieve my goals? 
What can I do differently to other people that makes me more employable? 
How can I go the extra mile?
How can I make opportunities happen for myself?

### Threats :
What could stop me from achieving my career goals? 
What do I need to stop doing now? 
What's out of my control that I can’t change?

### How to submit

Write and save your SWOT in a google doc. Attach the link to your ticket, but you don't have to make it public.

Share one thing from each category in your class thread.

**Comment by kfklein15** [comment]
This has been moved to JS3, so I will close it.
