### ISSUE TITLE
[PD] SMART

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Course-Fundamentals#11]
### Coursework content

https://www.youtube.com/watch?v=1-SvuFIQjK8

### Estimated time in hours

1

### What is the purpose of this assignment?

Now that you have envisioned the person you want to become and have a clear insight into your SWOT, it’s time to set some clear goals that will help you stay accountable and work towards achieving your personal and professional career ambitions. 

### Set SMART goals: 
Specific  - Be explicit about what you want to achieve.
Measurable - Make sure you can measure your progress. 
Achievable - Make sure that it’s realistic and attainable. 
Relevant - Don’t get a goal that is out of context to your career journey! 
Time bound - Give yourself a clear deadline.

### How to submit

1. Write in a google doc in your own Drive.
2. When you are ready, move to your class Drive.
3. Attach a link to this ticket.

**Comment by kfklein15** [comment]
This moved to HTML W3.
