### ISSUE TITLE
[PD] Start Using LinkedIn

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Course-Fundamentals#13]
### Coursework content

https://www.linkedin.com/

### Estimated time in hours

1

### What is the purpose of this assignment?

Professional communication is critical when it comes to landing a role. Employers are looking for passionate candidates. They use platforms like LinkedIn to find people.

### Stretch goal: 
Set up your LinkedIn profile and let employers know that you have started your journey into the tech industry. Communicate one of your smart goals, but make sure that it’s relevant to landing a role as a developer.

### How to submit

Put your LinkedIn on your Github Profile and link it on your copy of this ticket.

### Anything else?

If it's not safe for you to share your name online, you can skip this task. If you just cannot share your photo, use [Robohash](https://robohash.org/).

Read: https://docs.codeyourfuture.io/organisation/agreements-and-rules/naming-accounts-consistently

**Comment by kfklein15** [comment]
We moved this way ahead, only to JS3 W1. I would like your input, @SallyMcGrath , if you think we should keep the creation of it here anyway - we won't be doing much until JS3 though.
