### ISSUE TITLE
[PD] English Language test

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Course-Fundamentals#14]
### Coursework content

https://forms.gle/NZJ1U7vfKgHqCK857

### Estimated time in hours

1

### What is the purpose of this assignment?

Most people at Code Your Future speak English as a second language. All trainees will get lots of help and practise, but we do not have the expertise to teach English. Our expertise is in teaching programming languages.

We have learned that applicants with an English level of B1 or lower cannot follow our Software Development Course successfully. It is better to return to take this course once you have reached B2, rather than fail the course altogether. 

We will be here when you are ready.

### How to submit

1. Take the test linked on the form.
2. Submit your level on the form.

**Comment by kfklein15** [comment]
English Test to be done before being accepted in Fundamentals.
