### ISSUE TITLE
[PD] Apply to join the Software Development Course

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Course-Fundamentals#15]
### Coursework content

https://syllabus.codeyourfuture.io/fundamentals/graduation/criteria

### Estimated time in hours

2

### What is the purpose of this assignment?

If you have completed Fundamentals and would like to continue, apply to join the Software Development Course (SDC).

Read the criteria and next steps carefully.

### How to submit

Use the application form provided.

**Comment by maz786** [comment]
Kamino cloned this issue to [maz786/Coursework-Planner](https://github.com/maz786/Coursework-Planner/issues/14)

**Comment by haythem-f** [comment]
Kamino cloned this issue to [haythem-f/Coursework-Planner](https://github.com/haythem-f/Coursework-Planner/issues/8)

**Comment by nohetekelmariyam** [comment]
Kamino cloned this issue to [nohetekelmariyam/Coursework-Planner](https://github.com/nohetekelmariyam/Coursework-Planner/issues/15)

**Comment by RbAvci** [comment]
Kamino cloned this issue to [RbAvci/Coursework-Planner](https://github.com/RbAvci/Coursework-Planner/issues/20)

**Comment by Sabella-8** [comment]
Kamino cloned this issue to [Sabella-8/Courseworkplanner](https://github.com/Sabella-8/Courseworkplanner/issues/18)

**Comment by Ayman-matoo** [comment]
Kamino cloned this issue to [Ayman-matoo/Coursework-Planner](https://github.com/Ayman-matoo/Coursework-Planner/issues/18)

**Comment by kfklein15** [comment]
This is a duplicate with https://github.com/CodeYourFuture/Course-Fundamentals/issues/28
