### ISSUE TITLE
[PD] Agreements

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Course-Fundamentals#16]
### Coursework content

https://docs.codeyourfuture.io/organisation/agreements-and-rules/student-agreement

### Estimated time in hours

1

### What is the purpose of this assignment?

Agreements
You must read and agree to these rules before attending Code Your Future.

- [ ] [Trainee Agreement](https://docs.codeyourfuture.io/organisation/agreements-and-rules/student-agreement)
- [ ] [Code of Conduct](https://codeyourfuture.io/about/code-of-conduct/)
- [ ] [House Rules](https://docs.codeyourfuture.io/organisation/agreements-and-rules/house-rules)

If you have concerns or questions, please contact your cohort team. They will be happy to talk to you about our rules and what they mean for you.

Please sign the trainee agreement before coming to class.

### How to submit

Sign the agreement on Eversign https://codeyourfuture.eversign.com/embedded/a4062d0361324f7f97cba1105f164b24

Make sure you have read and agree to it first!

**Comment by kfklein15** [comment]
This has been added to the PD prep for this week.
PD Link: https://github.com/CodeYourFuture/CYF-PD/tree/main/content/blocks/agreements
[Curriculum PR ](https://github.com/CodeYourFuture/curriculum/pull/30)
Can I close it, @SallyMcGrath?
