### ISSUE TITLE
[PD] Developers daily activities

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Course-Fundamentals#26]
### Coursework content

Research a developer's daily **activities** and **behaviours**. What will you expect to know or do when you get your first job?

Activities are specific actions, tasks, or operations to accomplish a particular goal or objective.
- For example: A marketing analyst must conduct market research and data analysis to identify consumer trends

Behaviour is the observable actions, reactions, or conduct of someone.
- For example: A marketing analyst must be able to effectively communicate complex data clearly and understandably to stakeholders. 

### Estimated time in hours

1

### What is the purpose of this assignment?

- [ ] Research a developer's daily activities and behaviours 
- [ ] Write at least 50 words on a Google Docs file
- [ ] Check the grammar using an available too, for example, Grammarly
- [ ] Share the file with your cohort on the "Developers daily activities" thread. If the thread doesn't exist yet, create it.
- [ ] Read two contents shared with you
- [ ] Leave at least 2 comments or questions on each text you read

### How to submit

Add the link to your Google Docs
Add a screenshot of your post sharing your coursework

**Comment by maz786** [comment]
Kamino cloned this issue to [maz786/Coursework-Planner](https://github.com/maz786/Coursework-Planner/issues/10)

**Comment by kfklein15** [comment]
Closing this since we created a new one in induction
