### ISSUE TITLE
[PD] Trainee data collection WEST MIDLANDS ONLY

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Course-Fundamentals#27]
### Coursework content

We need you to give us some data about yourself, so that we can give you the best support as well as have all data available for our audits.

### Estimated time in hours

0.5

### What is the purpose of this assignment?

- Fill in [this form](https://docs.google.com/forms/d/e/1FAIpQLSdayyRzRX9tu4r_ETL4G_oMauSGbtx98FkwE0GzbZ4yhTbplQ/viewform) with your most up-to-date and accurate information

### How to submit

N/A

**Comment by RbAvci** [comment]
Kamino cloned this issue to [RbAvci/Coursework-Planner](https://github.com/RbAvci/Coursework-Planner/issues/8)

**Comment by nohetekelmariyam** [comment]
Kamino cloned this issue to [nohetekelmariyam/Coursework-Planner](https://github.com/nohetekelmariyam/Coursework-Planner/issues/1)

**Comment by illicitonion** [comment]
This is no longer required! 🎉
