### ISSUE TITLE
[TECH ED] Blockers!

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Course-Fundamentals#4]
### Link to the coursework

https://www.linkedin.com/pulse/how-overcome-coding-blockers-kingsley-ibe/

### Why are we doing this?

Next week in class we will talk about Iteration and Blockers. Look over the syllabus and prepare by reading Overcoming Blockers.

### Maximum time in hours

1

### How to submit

Write 1-2 bullet points on this ticket reflecting on the content. Move your ticket to "Done" when you're done.

**Comment by SpectacularLandscape** [comment]
Hi @SallyMcGrath, this issue appears in the Course Fundamental's repo "Issues" but not in the [Fundamentals Project](https://github.com/orgs/CodeYourFuture/projects/88). That's caused some confusion, is it possible to close this issue? I see it's not in the Fundamentals Course curriculum backlog either
